# Creation of the Datasets for classification: Binary 

Completed

In [11]:
import os
import numpy as np
import pandas as pd

import torch

In [59]:
dataset = "lemon"

In [60]:
folder_path = "/vol/aimspace/users/dena/Documents/mae/data/lemon"

data_raw_test = torch.load(os.path.join(folder_path, "data_raw_test.pt"))
data_raw_train = torch.load(os.path.join(folder_path, "data_raw_train.pt"))
data_raw_val = torch.load(os.path.join(folder_path, "data_raw_val.pt"))

labels_raw_test = torch.load(os.path.join(folder_path, "labels_raw_test.pt"))
labels_raw_train = torch.load(os.path.join(folder_path, "labels_raw_train.pt"))
labels_raw_val = torch.load(os.path.join(folder_path, "labels_raw_val.pt"))

In [66]:
save_path = f"/vol/aimspace/users/dena/Documents/ad_benchmarking/ad_benchmarking/data/{dataset}"

if not os.path.exists(save_path):
    os.makedirs(save_path)

In [67]:
# Approximate (!) mean age
mean_age = labels_raw_test.mean()

In [68]:
mask = labels_raw_val > mean_age
labels_bin_val = mask * torch.ones(labels_raw_val.shape)
torch.save(labels_bin_val, os.path.join(save_path, "labels_bin_val.pt"))

mask = labels_raw_train > mean_age
labels_bin_train = mask * torch.ones(labels_raw_train.shape)
torch.save(labels_bin_train, os.path.join(save_path, "labels_bin_train.pt"))

mask = labels_raw_test > mean_age
labels_bin_test = mask * torch.ones(labels_raw_test.shape)
torch.save(labels_bin_test, os.path.join(save_path, "labels_bin_test.pt"))


In [69]:
# labels_bin_val
# labels_bin_train
# labels_bin_test

# Creation of the Datasets for classification: Not-binary, but categorized

Completed

In [70]:
import os
import numpy as np
import pandas as pd
import torch

folder_path = "/vol/aimspace/users/dena/Documents/mae/data/lemon"

data_raw_test = torch.load(os.path.join(folder_path, "data_raw_test.pt"))
data_raw_train = torch.load(os.path.join(folder_path, "data_raw_train.pt"))
data_raw_val = torch.load(os.path.join(folder_path, "data_raw_val.pt"))

labels_raw_test = torch.load(os.path.join(folder_path, "labels_raw_test.pt"))
labels_raw_train = torch.load(os.path.join(folder_path, "labels_raw_train.pt"))
labels_raw_val = torch.load(os.path.join(folder_path, "labels_raw_val.pt"))

In [71]:
# Function to perform one-hot encoding
def one_hot_encode(labels, num_bins=20):
    
    encoded_labels = [] 
    for label_value in labels.flatten().numpy():
        bin_index = int(label_value / (100 / num_bins))
        if bin_index > num_bins-1: # if f.e. age is 100 or bigger: 
            bin_index = num_bins-1

        one_hot_vector = np.zeros(num_bins)
        one_hot_vector[bin_index] = 1
        encoded_labels.append(one_hot_vector)

    return encoded_labels

In [72]:
encoded_labels = one_hot_encode(labels_raw_test) 
list_of_tensors = [torch.from_numpy(arr) for arr in encoded_labels]
tensor_stack = torch.stack(list_of_tensors)

print("One-Hot Encoded Labels:")
for label, encoded_label in zip(labels_raw_test, encoded_labels):
    print(f"{label}: {encoded_label}")

One-Hot Encoded Labels:
tensor([22.5000]): [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
tensor([72.5000]): [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
tensor([27.5000]): [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
tensor([67.5000]): [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
tensor([67.5000]): [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
tensor([27.5000]): [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
tensor([22.5000]): [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
tensor([67.5000]): [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
tensor([57.5000]): [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
tensor([22.5000]): [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
tensor([22.5000]): [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
tensor([22.5000]): [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
tens

In [73]:
tensor_stack
save_path = f"/vol/aimspace/users/dena/Documents/ad_benchmarking/ad_benchmarking/data/{dataset}"
data_type_name = "categorized"

encoded_labels = one_hot_encode(labels_raw_val) 
list_of_tensors = [torch.from_numpy(arr) for arr in encoded_labels]
labels_bin_val = torch.stack(list_of_tensors)
torch.save(labels_bin_val, os.path.join(save_path, f"labels_{data_type_name}_val.pt"))

encoded_labels = one_hot_encode(labels_raw_train) 
list_of_tensors = [torch.from_numpy(arr) for arr in encoded_labels]
labels_bin_train = torch.stack(list_of_tensors)
torch.save(labels_bin_train, os.path.join(save_path, f"labels_{data_type_name}_train.pt"))

encoded_labels = one_hot_encode(labels_raw_test) 
list_of_tensors = [torch.from_numpy(arr) for arr in encoded_labels]
labels_bin_test = torch.stack(list_of_tensors)
torch.save(labels_bin_test, os.path.join(save_path, f"labels_{data_type_name}_test.pt"))

# labels_bin_val.shape
# print(labels_bin_train[:10])
# labels_bin_test